ALTER TABLE productos 
ADD COLUMN destacado BOOLEAN DEFAULT false,
ADD COLUMN oferta BOOLEAN DEFAULT false,
ADD COLUMN nuevo BOOLEAN DEFAULT false;

UPDATE productos SET destacado = true WHERE id IN (1, 3, 5, 7, 9);
UPDATE productos SET oferta = true WHERE id IN (2, 4, 6, 8, 10);
UPDATE productos SET nuevo = true WHERE id IN (11, 13, 15, 17, 19);

ALTER TABLE producto_imagenes 
ADD COLUMN id BIGSERIAL PRIMARY KEY,
ADD COLUMN es_principal BOOLEAN DEFAULT false,
ADD COLUMN orden INTEGER DEFAULT 0,
ADD COLUMN fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE producto_imagenes 
SET es_principal = true 
WHERE id IN (
  SELECT min(id) FROM producto_imagenes GROUP BY producto_id
);

-- Nuevos productos para cumplir con 8 por cada de las 10 categorías
-- Las 10 categorías son: Periféricos, Monitores, Laptops, Audio, Muebles, Accesorios, Redes, Gaming, Almacenamiento, Smart Home
-- Inserto registros de prueba genéricos para completar
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (20, 'Producto Genérico Periféricos 1', 'Descripción autogenerada para completar catálogo', 442751, 58, 'Periféricos', 'ACTIVO', 3.9, 3, 31, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (20, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (21, 'Producto Genérico Periféricos 2', 'Descripción autogenerada para completar catálogo', 409341, 91, 'Periféricos', 'ACTIVO', 3.8, 12, 128, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (21, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (22, 'Producto Genérico Periféricos 3', 'Descripción autogenerada para completar catálogo', 371624, 36, 'Periféricos', 'ACTIVO', 4.7, 22, 224, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (22, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (23, 'Producto Genérico Periféricos 4', 'Descripción autogenerada para completar catálogo', 251209, 37, 'Periféricos', 'ACTIVO', 3.6, 49, 499, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (23, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (24, 'Producto Genérico Periféricos 5', 'Descripción autogenerada para completar catálogo', 100869, 90, 'Periféricos', 'ACTIVO', 3.8, 43, 433, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (24, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (25, 'Producto Genérico Monitores 1', 'Descripción autogenerada para completar catálogo', 387622, 96, 'Monitores', 'ACTIVO', 3.9, 37, 373, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (25, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (26, 'Producto Genérico Monitores 2', 'Descripción autogenerada para completar catálogo', 212230, 18, 'Monitores', 'ACTIVO', 4.9, 42, 426, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (26, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (27, 'Producto Genérico Monitores 3', 'Descripción autogenerada para completar catálogo', 238537, 62, 'Monitores', 'ACTIVO', 3.7, 36, 366, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (27, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (28, 'Producto Genérico Monitores 4', 'Descripción autogenerada para completar catálogo', 203074, 87, 'Monitores', 'ACTIVO', 4.6, 15, 156, NOW(), NOW(), 0, true, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (28, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (29, 'Producto Genérico Monitores 5', 'Descripción autogenerada para completar catálogo', 386403, 38, 'Monitores', 'ACTIVO', 4.1, 27, 273, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (29, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (30, 'Producto Genérico Laptops 1', 'Descripción autogenerada para completar catálogo', 20760, 23, 'Laptops', 'ACTIVO', 4.2, 30, 306, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (30, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (31, 'Producto Genérico Laptops 2', 'Descripción autogenerada para completar catálogo', 335706, 78, 'Laptops', 'ACTIVO', 4.9, 2, 28, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (31, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (32, 'Producto Genérico Laptops 3', 'Descripción autogenerada para completar catálogo', 460302, 84, 'Laptops', 'ACTIVO', 4.7, 11, 112, NOW(), NOW(), 0, true, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (32, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (33, 'Producto Genérico Laptops 4', 'Descripción autogenerada para completar catálogo', 462128, 21, 'Laptops', 'ACTIVO', 4.7, 17, 177, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (33, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (34, 'Producto Genérico Laptops 5', 'Descripción autogenerada para completar catálogo', 232460, 33, 'Laptops', 'ACTIVO', 4.9, 35, 351, NOW(), NOW(), 0, true, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (34, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (35, 'Producto Genérico Audio 1', 'Descripción autogenerada para completar catálogo', 188861, 90, 'Audio', 'ACTIVO', 3.5, 4, 49, NOW(), NOW(), 0, true, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (35, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (36, 'Producto Genérico Audio 2', 'Descripción autogenerada para completar catálogo', 172231, 58, 'Audio', 'ACTIVO', 4.9, 36, 369, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (36, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (37, 'Producto Genérico Audio 3', 'Descripción autogenerada para completar catálogo', 74329, 17, 'Audio', 'ACTIVO', 3.9, 34, 345, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (37, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (38, 'Producto Genérico Audio 4', 'Descripción autogenerada para completar catálogo', 477921, 70, 'Audio', 'ACTIVO', 4.6, 43, 435, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (38, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (39, 'Producto Genérico Audio 5', 'Descripción autogenerada para completar catálogo', 113381, 14, 'Audio', 'ACTIVO', 4.4, 27, 274, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (39, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (40, 'Producto Genérico Muebles 1', 'Descripción autogenerada para completar catálogo', 263474, 43, 'Muebles', 'ACTIVO', 4.7, 7, 75, NOW(), NOW(), 0, true, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (40, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (41, 'Producto Genérico Muebles 2', 'Descripción autogenerada para completar catálogo', 456328, 99, 'Muebles', 'ACTIVO', 3.8, 25, 258, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (41, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (42, 'Producto Genérico Muebles 3', 'Descripción autogenerada para completar catálogo', 237881, 42, 'Muebles', 'ACTIVO', 4.5, 20, 206, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (42, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (43, 'Producto Genérico Muebles 4', 'Descripción autogenerada para completar catálogo', 64931, 42, 'Muebles', 'ACTIVO', 3.6, 25, 252, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (43, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (44, 'Producto Genérico Muebles 5', 'Descripción autogenerada para completar catálogo', 442920, 100, 'Muebles', 'ACTIVO', 4.9, 39, 392, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (44, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (45, 'Producto Genérico Accesorios 1', 'Descripción autogenerada para completar catálogo', 233792, 68, 'Accesorios', 'ACTIVO', 4.9, 48, 484, NOW(), NOW(), 0, true, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (45, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (46, 'Producto Genérico Accesorios 2', 'Descripción autogenerada para completar catálogo', 47248, 51, 'Accesorios', 'ACTIVO', 4.0, 44, 441, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (46, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (47, 'Producto Genérico Accesorios 3', 'Descripción autogenerada para completar catálogo', 121626, 43, 'Accesorios', 'ACTIVO', 4.1, 26, 268, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (47, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (48, 'Producto Genérico Accesorios 4', 'Descripción autogenerada para completar catálogo', 211488, 34, 'Accesorios', 'ACTIVO', 4.6, 44, 443, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (48, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (49, 'Producto Genérico Accesorios 5', 'Descripción autogenerada para completar catálogo', 490318, 86, 'Accesorios', 'ACTIVO', 4.8, 20, 201, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (49, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (50, 'Producto Genérico Redes 1', 'Descripción autogenerada para completar catálogo', 236625, 22, 'Redes', 'ACTIVO', 4.9, 14, 147, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (50, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (51, 'Producto Genérico Redes 2', 'Descripción autogenerada para completar catálogo', 134409, 79, 'Redes', 'ACTIVO', 4.3, 33, 331, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (51, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (52, 'Producto Genérico Redes 3', 'Descripción autogenerada para completar catálogo', 102038, 40, 'Redes', 'ACTIVO', 4.4, 29, 298, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (52, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (53, 'Producto Genérico Redes 4', 'Descripción autogenerada para completar catálogo', 334092, 20, 'Redes', 'ACTIVO', 4.0, 31, 316, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (53, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (54, 'Producto Genérico Redes 5', 'Descripción autogenerada para completar catálogo', 227872, 90, 'Redes', 'ACTIVO', 4.3, 25, 251, NOW(), NOW(), 0, true, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (54, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (55, 'Producto Genérico Redes 6', 'Descripción autogenerada para completar catálogo', 229550, 38, 'Redes', 'ACTIVO', 3.8, 18, 187, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (55, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (56, 'Producto Genérico Redes 7', 'Descripción autogenerada para completar catálogo', 309809, 72, 'Redes', 'ACTIVO', 4.5, 27, 278, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (56, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (57, 'Producto Genérico Redes 8', 'Descripción autogenerada para completar catálogo', 77518, 62, 'Redes', 'ACTIVO', 5.0, 20, 207, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (57, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (58, 'Producto Genérico Gaming 1', 'Descripción autogenerada para completar catálogo', 468263, 93, 'Gaming', 'ACTIVO', 4.2, 34, 345, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (58, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (59, 'Producto Genérico Gaming 2', 'Descripción autogenerada para completar catálogo', 134201, 23, 'Gaming', 'ACTIVO', 3.6, 3, 31, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (59, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (60, 'Producto Genérico Gaming 3', 'Descripción autogenerada para completar catálogo', 447939, 58, 'Gaming', 'ACTIVO', 4.0, 47, 477, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (60, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (61, 'Producto Genérico Gaming 4', 'Descripción autogenerada para completar catálogo', 381065, 76, 'Gaming', 'ACTIVO', 4.0, 5, 54, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (61, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (62, 'Producto Genérico Gaming 5', 'Descripción autogenerada para completar catálogo', 470176, 13, 'Gaming', 'ACTIVO', 4.6, 20, 209, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (62, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (63, 'Producto Genérico Gaming 6', 'Descripción autogenerada para completar catálogo', 469189, 74, 'Gaming', 'ACTIVO', 4.9, 33, 336, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (63, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (64, 'Producto Genérico Gaming 7', 'Descripción autogenerada para completar catálogo', 247602, 29, 'Gaming', 'ACTIVO', 4.6, 26, 266, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (64, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (65, 'Producto Genérico Gaming 8', 'Descripción autogenerada para completar catálogo', 446729, 10, 'Gaming', 'ACTIVO', 4.8, 19, 194, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (65, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (66, 'Producto Genérico Almacenamiento 1', 'Descripción autogenerada para completar catálogo', 229222, 20, 'Almacenamiento', 'ACTIVO', 4.3, 27, 271, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (66, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (67, 'Producto Genérico Almacenamiento 2', 'Descripción autogenerada para completar catálogo', 82021, 68, 'Almacenamiento', 'ACTIVO', 4.8, 14, 143, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (67, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (68, 'Producto Genérico Almacenamiento 3', 'Descripción autogenerada para completar catálogo', 459615, 25, 'Almacenamiento', 'ACTIVO', 4.9, 42, 426, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (68, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (69, 'Producto Genérico Almacenamiento 4', 'Descripción autogenerada para completar catálogo', 461250, 87, 'Almacenamiento', 'ACTIVO', 4.4, 44, 443, NOW(), NOW(), 0, true, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (69, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (70, 'Producto Genérico Almacenamiento 5', 'Descripción autogenerada para completar catálogo', 174954, 36, 'Almacenamiento', 'ACTIVO', 4.1, 46, 461, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (70, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (71, 'Producto Genérico Almacenamiento 6', 'Descripción autogenerada para completar catálogo', 80760, 56, 'Almacenamiento', 'ACTIVO', 3.6, 46, 463, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (71, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (72, 'Producto Genérico Almacenamiento 7', 'Descripción autogenerada para completar catálogo', 215727, 46, 'Almacenamiento', 'ACTIVO', 4.4, 19, 192, NOW(), NOW(), 0, true, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (72, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (73, 'Producto Genérico Almacenamiento 8', 'Descripción autogenerada para completar catálogo', 330036, 11, 'Almacenamiento', 'ACTIVO', 4.1, 34, 343, NOW(), NOW(), 0, true, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (73, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (74, 'Producto Genérico Smart Home 1', 'Descripción autogenerada para completar catálogo', 380366, 88, 'Smart Home', 'ACTIVO', 3.7, 37, 373, NOW(), NOW(), 0, true, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (74, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (75, 'Producto Genérico Smart Home 2', 'Descripción autogenerada para completar catálogo', 97058, 42, 'Smart Home', 'ACTIVO', 3.9, 47, 470, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (75, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (76, 'Producto Genérico Smart Home 3', 'Descripción autogenerada para completar catálogo', 168749, 41, 'Smart Home', 'ACTIVO', 4.5, 13, 132, NOW(), NOW(), 0, false, true, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (76, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (77, 'Producto Genérico Smart Home 4', 'Descripción autogenerada para completar catálogo', 83538, 27, 'Smart Home', 'ACTIVO', 4.6, 48, 487, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (77, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (78, 'Producto Genérico Smart Home 5', 'Descripción autogenerada para completar catálogo', 432111, 22, 'Smart Home', 'ACTIVO', 3.7, 19, 198, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (78, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (79, 'Producto Genérico Smart Home 6', 'Descripción autogenerada para completar catálogo', 311858, 33, 'Smart Home', 'ACTIVO', 4.0, 38, 383, NOW(), NOW(), 0, true, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (79, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (80, 'Producto Genérico Smart Home 7', 'Descripción autogenerada para completar catálogo', 294873, 83, 'Smart Home', 'ACTIVO', 4.5, 31, 312, NOW(), NOW(), 0, false, false, true);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (80, 'assets/images/product-placeholder.webp', true, 1, NOW());
INSERT INTO productos (id, nombre, descripcion, precio, stock, categoria, estado, rating_promedio, total_ratings, cantidad_vendidos, fecha_creacion, fecha_actualizacion, version, destacado, oferta, nuevo) VALUES (81, 'Producto Genérico Smart Home 8', 'Descripción autogenerada para completar catálogo', 170407, 96, 'Smart Home', 'ACTIVO', 4.9, 16, 169, NOW(), NOW(), 0, false, false, false);
INSERT INTO producto_imagenes (producto_id, imagen_url, es_principal, orden, fecha_creacion) VALUES (81, 'assets/images/product-placeholder.webp', true, 1, NOW());
SELECT setval('productos_id_seq', 83);
