server.port=8081
server.address=0.0.0.0

# ===================== DATABASE (POSTGRES) =====================
spring.datasource.url=jdbc:postgresql://postgres:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================== JPA / HIBERNATE =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================== KAFKA =====================
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.smartlogix.inventory.event.CompraEvent

# ===================== SECURITY (AUTH0) =====================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-nomnv0fhn3zpzt4t.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://smartlogix-api

# ===================== LOGS =====================
logging.level.org.springframework.kafka=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=INFO