server.port=8081
server.address=0.0.0.0

# ===================== DATABASE (POSTGRES) =====================
spring.datasource.url=jdbc:postgresql://postgres:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================== JPA / HIBERNATE =====================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================== FLYWAY =====================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ===================== KAFKA =====================
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.smartlogix.inventory.event.CompraEvent

# ===================== KAFKA RETRY & DLT =====================
# Deshabilitar auto-commit para control manual de offset
spring.kafka.consumer.enable-auto-commit=false
# Acknowledge mode: RECORD permite reintentos antes de commitear
spring.kafka.listener.ack-mode=RECORD

# ===================== SECURITY (AUTH0) =====================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/
spring.security.oauth2.resourceserver.jwt.audience=${AUTH0_AUDIENCE}

# ===================== LOGS =====================
logging.level.org.springframework.kafka=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.security=INFO

# ================= OPTIMIZACIONES ARRANQUE ================= 
spring.main.lazy-initialization=true

logging.level.root=INFO

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.jmx.enabled=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
