server.port=8080
server.address=0.0.0.0

spring.application.name=bff-service

services.inventory.url=${SERVICES_INVENTORY_URL:${INVENTORY_SERVICE_URL:http://localhost:8081}}
services.pedidos.url=${SERVICES_PEDIDOS_URL:${PEDIDOS_SERVICE_URL:http://localhost:8082}}
services.usuarios.url=${SERVICES_USUARIOS_URL:${USUARIOS_SERVICE_URL:http://localhost:8083}}
services.envios.url=${SERVICES_ENVIOS_URL:${ENVIO_SERVICE_URL:http://localhost:8084}}

# AUTH0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/
auth0.audience=${AUTH0_AUDIENCE}

# LOGS
logging.level.root=INFO
logging.level.com.smartlogix.bff=INFO
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=INFO
logging.level.org.springframework.web=INFO
logging.level.reactor.netty.http.client=INFO

# ACTUATOR
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# JACKSON
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.default-property-inclusion=non_null

# OPTIMIZACIONES
spring.main.lazy-initialization=true
spring.jmx.enabled=false
