server.port=8080
server.address=0.0.0.0

spring.application.name=bff-service

# =========================
# MICROSERVICIOS (SOLO VARIABLES)
# =========================
services.inventory.url=${SERVICES_INVENTORY_URL:http://inventory-service:8081}
services.pedidos.url=${SERVICES_PEDIDOS_URL:http://pedidos-service:8082}
services.usuarios.url=${SERVICES_USUARIOS_URL:http://usuarios-service:8083}

# =========================
# AUTH0
# =========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-nomnv0fhn3zpzt4t.us.auth0.com/

# =========================
# LOGS
# =========================
logging.level.root=INFO
logging.level.com.smartlogix.bff=DEBUG

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =========================
# JACKSON
# =========================
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false