server.port=8082
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://postgres:5432/pedidos_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-nomnv0fhn3zpzt4t.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://smartlogix-api

management.endpoints.web.exposure.include=health,metrics,prometheus,info,circuitbreakers
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true